### ISSUE TITLE
Start - Open Source Circle @ IPST

### ISSUE THREAD

**Issue by MarkusTiede** [bfh/open-source#10]
Community involvement - mailing list : https://community.finos.org/docs/journey/learn/#not-sure-where-to-get-started

Community of interest >> Community of practice 
- https://www.scaledagileframework.com/communities-of-practice/
- https://github.com/redhat-cop

My experience the last 6 years: https://github.com/baloise/open-source/blob/main/docs/md/goals/join.md#meet--greet

Gedankenmodell: https://baloise.github.io/open-source/docs/arc42/#_overview

**Comment by mauriziopiu** [comment]
# Circle Planning

## Circle Sheet

### Circle Basics

Name des Circles: Open Source Technologies
Circle Lead: Maurizio Piu
Circle Mitglieder: Aaron Sägesser, (Markus Tiede, Dominic Schweizer, Ronny Standtke)
Start des Circle: Oktober 22

Stundenverteilung pro Jahr: 
*(X Stunden total für die nächsten 12 Monate)*
max. 48h Organisation + max. 96h Beitragszeit = 144h

*(davon X Stunden an Leader)*
ca. 4h pro Monat für Koordination, Planung etc
ca. 48h pro Jahr

*(und X Stunden per Mitglied)*
1-2 Stunden per Newsletter-Beitrag
3-4 Beiträge pro Monat (fürs erste)
36-48 Beiträge Pro Jahr

36-48 Stunden Pro Jahr bei 1h per Newsletter-Beitrag
72-96 Stunden Pro Jahr bei 2h per Newsletter-Beitrag

### Zielsetzungen und Nutzen fürs IPST

Informationsaustausch und Kenntnisstand erhöhen über (Open Source) Software, Websites, Frameworks/Libraries, kreative Problemlösungen oder sonstige Tools aus dem Kontext von Open Source (Entwicklung).

Interdisziplinärer Austausch und Kontaktfläche für neue Technologien bieten.

### Thematische Eingrenzung

Headline Themen: "Open Source Software" (+ "Digitale Nachhaltigkeit")

Jegliche technologischen Mittel, welche **Open Source in der Methodik** verwenden (z.B. Open Source Library für Problem X) bestenfalls um **digitale Nachhaltigkeit als Ziel** zu verfolgen.

(Ausführlicher hier: [[#Was kommt in den Beitrag]])

### Aktivitäten und Zielgruppen

### Aktivitäten

Hauptaktivität: Regelmässig (ca. monatlich) eine Rundmail an alle aktiven und passiven Mitglieder verfassen.

Evt. Aktivität: Beiträge öffentlich auf einer Plattform publizieren

(( Evt. Nebenaktivität: Aus besonders gelungenen Beiträgen welche sich an thematisch an einem ähnlichen oder gleichen Ort befinden Infografik Plakate erstellen, die man aufhängen könnte. ))

### Zielgruppen

Grundsätzlich sicher IPST und DSL intern, das Prinzip lässt sich aber auch öffnen für BFH-W, BFH, CH Open, etc.

### Vorgehen und nächste Schritte

- [ ] Circle Idee ausarbeiten
- [ ] Circle Sheet ausfüllen
- [ ] Pitchen
- [ ] Nach OK vom Management
	- [ ] Info Mail an DSL und IPST für Interessent\*innen für aktive/passive Mitgliedschaft - Rückmeldung bis zu einem bestimmten Termin
- [ ] Sobald klar ist wer teilnimmt
	- [ ] 3 Personen für erste Circle Mail bestimmen
	- [ ] Cycle Termine bestimmen
		- [ ] Wann wird gefragt ob jemand einen Beitrag schreiben kann?
		- [ ] Bis wann muss ich wissen wer schreibt?
		- [ ] Bis wann brauche ich die Beiträge?
		- [ ] Wann wird das Mail versendet?


## Organisation

### Teilnehmende

Circle Lead: Maurizio Piu

Aktive Circle Mitglieder (bekommen Stunden für Beiträge): 
(in Klammern haben noch nicht zugesagt)

- Aaron Sägesser
- Dominic Schweizer
- Dominic Wenger
- Kerrie Stauffer
- (Markus Tiede)
  
Passive Circle Mitglieder (keine Stunden, dafür Mails nur lesen):

- (Myriam Wasmuth)
- 
  
## Circle Mail

Hauptaktivität des Circles. 3-4 Personen welche als aktive Mitglieder im Circle sind, verfassen eine kurzen (ca 100-300 Wörter, so viel wie man selbst darüber lesen würde), "Blogpost"-mässigen Beitrag zu einer Software, einem Tool etc. was andere evt. noch nicht kennen könnten.

### Was kommt in den Beitrag?

Hauptthema des Circles ist "Open Source Software".

In diesem Zusammenhang ist die Idee, den anderen Mitgliedern des Circles eine Software, Website, Framework/Library, kreative Problemlösung oder sonstige Tools vorzustellen. 

Diese sollte im Kontext von Open Source (Entwicklung) irgendeine Form von Relevanz haben und nicht vollständig aus diesem Kontext hinausgreifen. (Wenn man selbst irgendeinen konkreten Bezug zu diesem Thema herstellen kann, sollte das dann i.d.R. okay sein. Im Zweifelsfall entscheidet der Circle Lead). 

Viele im IPST und im Besonderen auch im DSL haben in Ihrem jeweiligen Alltag regelmässig mit solchen Technologien zu tun und ein Ziel dieses Circles ist es, den Informationsaustausch und Kenntnisstand über diese Themen zu fördern. So kann ein interdisziplinärer Austausch angeregt und eine Kontaktfläche für neue Technologien geboten werden.

Die Idee ist es, dass man einen Beitrag über ein Thema schreibt, zu welchem ein persönlicher Bezug besteht. Konkret heisst das man hat mit einer bestimmten Library gearbeitet, darüber gelesen oder ist sonstwie damit in Kontakt gekommen und haltet es für "share-worthy". Die Beiträge selbst sollten einer Person, welche noch nie mit dem konkretem Thema zu tun hatte, kurz erklären:

- Worum es geht
- Welche Probleme damit gelöst werden können
- Evt. Knackpunkte des Ganzen (z.B. "Kompatibilitätsprobleme mit Angular 14.1.0")
- Welchen persönlichen Bezug man dazu hat ("Ich habe für Projekt X die Technologie Y verwendet")
- Wie man den Einstieg findet? (Link zum GitHub Repo, o.Ä.)

### Wer schreibt die Beiträge?

Per Circle Mail halte ich 3-4 Beiträge für ausreichend. Da der Circle vermutlich auf mehr als 4 Mitglieder wachsen wird, werde ich (Circle Leader) koordinieren wer in welchem Monat Beiträge geschrieben hat. Für die Planung werde ich grundsätzlich innerhalb der aktiven Teilnehmer\*innenliste rotieren und Personen konkret fragen ob Sie für diesen Monat einen Beitrag schreiben können. Natürlich kann man auch auf mich zukommen, wenn man gerade eine Idee für einen Beitrag für den nächsten Monat hat, dann kann ich es einplanen. Ausgehend von eigenständigen Meldungen (bis zu einem bestimmten Datum) und dem Rotationsprinzip werde ich planen wer einen Beitrag für den nächsten Monat schreibt und bis wann ich die Texte/Links brauche. Diese Information werde ich den jeweiligen Personen dann zukommen lassen.

**Comment by mauriziopiu** [comment]
# CoP: Layers of involvement

## Core

- Operate the Circle (Meetings, Organize the news)

## Active

- Participate regularly in meetings, workshops etc
- Write about technologies regularly

## Occasional

- Write about technologies when something of interest occurs

## Peripheral

- Read about technologies handled
- May also write, if they want to
  
## Transactional

- Access our Resources
- Provide Services to our Circle

**Comment by MarkusTiede** [comment]
Repo: https://github.com/digital-sustainability/open-source-circle

**Comment by MarkusTiede** [comment]
Erster Austausch hat stattgefunden: https://github.com/digital-sustainability/open-source-circle/issues/1
