### ISSUE TITLE
«Kennenlern» Kick-Off Veranstaltung: "Open Source CoP @ BFH"

### ISSUE THREAD

**Issue by MarkusTiede** [bfh/open-source#12]
# Agenda

## (kurze) Vorstellungsrunde: Was verbindet euch mit der «BFH & Open Source»?
alphabetisch nach Vornamen
- ✅ @AnniqueLombard
- ✅ @Hannes-Ole
- ✅ @TheNuttree 
- ✅ @vgj1 - InnerSourcing? (gitlab & Co)
- ✅ @MarkusTiede
- ✅ @maemst 
- ✅ @mauriziopiu (deputy: Aaron, ...)
- ✅ @l00mi
- ✅ @MyriamWasmuth
- ✅ @ronnystandtke

## Kontext - Humane Digitale Transformation (HDT) Projekt

[Strategische Themenfelder ](https://www.bfh.ch/de/strategische-themenfelder/) > [Humane digitale Transformation](https://www.bfh.ch/de/strategische-themenfelder/digitalisierung/)

### 1. BFH Open Source Knowledge Platform
5+2 : https://ossbenchmark.com/institutions/bfh
 - https://github.com/digital-sustainability/open-source/issues/19
>> zB http://www.opensource.unibe.ch

### 2. Community (of Practice)

>> [“Culture Eats Strategy For Breakfast”](https://www.thealternativeboard.com/blog/culture-eats-strategy)

![](https://stagingv5.wpenginepowered.com/wp-content/uploads/2015/06/F1-Communities-of-practive-have-three_WP-1.png)

Orga: https://www.scaledagileframework.com/communities-of-practice/
Format: https://opensourcefriday.com
Board: https://github.com/orgs/bfh/projects/1

### kurzfristig Q1 & Q2 2023
- Community (of Communities?) etablieren
  - Vorschlag alle 2 Wochen Mittwochs von 11-12
- Wert (Nutzen) von Open Source @ BFH sichtbar machen: https://opensource.bfh.ch
  - https://github.com/digital-sustainability/open-source/issues/7  

![](https://baloise.github.io/open-source/docs/arc42/images/os-maturity-model.png)

### mittelfristig 2023 - 2024: Open Source @ BFH "Professionalisieren"

[![](https://github.com/todogroup/ospo-career-path/raw/main/OSPO%20101/ospo101.svg)](https://ospo101.org)
https://ossbenchmark.com/institutions/bfh

[Guidelines](https://baloise.github.io/open-source/docs/arc42/#_overview) & Policies im Kontext der BFH erarbeiten & vorleben 

## next steps
- https://github.com/digital-sustainability/open-source/issues/13
- https://github.com/digital-sustainability/open-source/issues/20
- regular exchange "Community of Communities"

## offene Fragen
- [...]
- [...]
- [...]
- [...]
- [...]

**Comment by MarkusTiede** [comment]
```
Guten Morgen Zusammen
 
Morgen treffen wir uns von 11-12 Uhr zu einem ersten, virtuellen Kennenlernen auf BBB:
 
https://bbb.ch-open.ch/b/mar-ttf-4g4
 
Wenn ihr noch nie auf BBB an einer Sitzung teilgenommen habt, klinkt euch doch gerne 5-10 früher ein, um «technisches Onboarding (Ton & Video)»  vorab zu erledigen.
 
Unsere kleine Agenda findet ihr hier: https://github.com/digital-sustainability/open-source/issues/12
 
Bitte
Stellt euch und das, was euch mit der «BFH & Open Source» verbindet, zu Anfang des Treffens (bspw. anhand eures Github-Profils / eines Links zu einem Projekt etc.) kurz vor – ich werde den Bildschirm teilen, ihr braucht sonst nichts mitzubringen
Sammelt ansonsten auch noch eure aktuellen Ideen & Fragen für das morgige Treffen (gerne auch vorab bspw. als Kommentar am obigen Issue).
 
Ich werde selber auch «nur» remote am Meeting (von der DINAcon - der Konferenz für Digitale Nachhaltigkeit morgen in Bern) teilnehmen – Myriam hat aber am IPST einen Raum organisiert, für die die sich bei uns vor Ort treffen.
 
Das war’s auch schon,
LG und bis dann
Markus
 
@Matthias, @Christian & @Annett : wenn ihr mögt, seid ihr natürlich auch herzlichen zum Kick-Off eingeladen; ich rechne zZ aber nicht zwingend mit eurer Teilnahme.
```

**Comment by ronnystandtke** [comment]
Wir haben sicherlich noch keine Gesamtsicht, da viele Mitarbeitenden noch persönliche Github-Accounts oder noch Konten auf anderen ähnlichen Diensten haben.
