### ISSUE TITLE
Create eMail shared Mailbox: opensource@bfh.ch

### ISSUE THREAD

**Issue by MarkusTiede** [bfh/open-source#15]
E.g. for
 - https://github.com/bfh/open-source/issues/60

**Comment by AnniqueLombard** [comment]
Wie wäre es mit opensource@bfh.ch? Ich melde mich bei Corinna wegen der Landingpage und kann diese Anfrage auch gleich auslösen. Wohin sollte diese e-mail umgeleitet werden?

**Comment by MarkusTiede** [comment]
@AnniqueLombard : Ja genau - die hätte ich auch genommen; 1:1 analog zur Sub-Domain.

Ich hätte eigentlich gerne keine Weiterleitung sondern eine von X-Personen bewirtschaftbare geteilte Mailbox: ist so etwas möglich? Dann kann eben eine ganze Gruppe / Community hier aktiv sein & werden.

**Comment by AnniqueLombard** [comment]
![image](https://user-images.githubusercontent.com/116714643/208625453-62fa628d-d253-4424-9235-5a05536e44ff.png)
Antrag genehmigt, Umsetzung sollte auch bald folgen mit Postfach und Zugriffen aktuell für Markus, Matthias, Annique, Myriam.

**Comment by lucaboesch** [comment]
bsl3 gerne

**Comment by AnniqueLombard** [comment]
Die e-mail-Box ist erstellt, die Test-Mail angekommen - nun regelt das nächste "Ticket" die Zugangsberechtigungen.

**Comment by AnniqueLombard** [comment]
Der Zugang für laa3 tem1 und smm15 sollte bereits funktionieren, yay! Die Mailbox wird automatisch in Outlook angezeigt. Danach muss man den aktiven Versand von dieser Adresse noch initiieren (hinzufügen bei den Account-Einstellungen). Bei Myriam und mir funktioniert das Empfangen und Senden. Den zusätzlichen Antrag für bsl3 ist noch hängig aber unterwegs.

**Comment by MarkusTiede** [comment]
Mein Zugang klappt ebenfalls - sehr gut!
